### PR TITLE
more libraries, move media to audio/video

### PR DESCRIPTION
**Pull request by nodiscc**

### CODE REVIEW

**Comment by nodiscc** [comment]
@sorrycc Ok to merge?

**Comment by nodiscc** [comment]
ping @sorrycc , ok to merge?

**Comment by huei90** [comment]
I prefer you separate the commit and specify the message instead of `more libraries`

**Comment by nodiscc** [comment]
I have separated the commits, with proper commit messages, see https://github.com/sorrycc/awesome-javascript/pull/331

**Pull request closed without merging**
