### PR TITLE
QA Tools -> add Standard

### PR DESCRIPTION
**Pull request by oprogramador**

### CODE REVIEW

**Comment by oprogramador** [comment]
@sorrycc @hueitan 

could you look into this?

**Comment by oprogramador** [comment]
@hueitan 

could you look into this?

**Comment by hueitan** [comment]
sure, can you rebase the branch?

**Comment by oprogramador** [comment]
@hueitan 

I rebased and resolved the conflict.

I see someone has already added a link to the Standard, however https://github.com/feross/standard redirects to https://github.com/standard/standard so I just changed the link.

**Comment by oprogramador** [comment]
@hueitan

**Comment by oprogramador** [comment]
@hueitan 

could you review/ merge?

**Pull request closed without merging**
