### PR TITLE
Add pm.js

### PR DESCRIPTION
**Pull request by lesismal**
Help To Build Single-Page App And Make Native Fastest!

### CODE REVIEW

**Review by gokaygurcan — CHANGES_REQUESTED** [review]
No line cutting please. First come, first serve.

**Comment by lesismal** [comment]
> No line cutting please. First come, first serve.

Sorry, I do not understand what you mean. How about if I change it to this: 

pm.js - Page Manager, help to build single page app & make native fastest!

**Comment by gokaygurcan** [comment]
I mean, "please add new links at the end of their block, not somewhere in between". I hope this time it's more clear.
Thanks!

**Comment by lesismal** [comment]
> I mean, "please add new links at the end of their block, not somewhere in between". I hope this time it's more clear.
> Thanks!

ok, I will close this and pr again, thanks for your explanation

**Pull request closed without merging**
