### PR TITLE
Add Vizzu

### PR DESCRIPTION
**Pull request by simzer**
Checklist:

- [x] I've read and understood [Contributing Guidelines](CONTRIBUTING.md).
- [x] I've added the new resource at the end of its section.
- [x] This resource is out there for a while, and actively maintained.
- [x] This resource is popular enough and has at least a few hundred stars on GitHub.

---

Vizzu is a new open-source dataviz library with a focus on animation.

### CODE REVIEW

**Comment by gokaygurcan** [comment]
Hi @simzer,

Can you please resolve the conflicts? And please say hi to Peter.

Cheers

**Comment by Ashe-reset** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by simzer** [comment]
Hi @gokaygurcan,
Happy New Year!
I've fixed the conflict.

**Comment by simzer** [comment]
Oops, sorry, not yet.

**Comment by simzer** [comment]
Now it's OK, I believe.

**Pull request merged**
