### PR TITLE
Added mxGraph - diagramming library.

### PR DESCRIPTION
**Pull request by alundiak**
More info here: https://jgraph.github.io/mxgraph/

### CODE REVIEW

**Comment by alundiak** [comment]
Since 2017 - no one to approve? Or at least decline saying it's not worth having on page maybe?

**Comment by gokaygurcan** [comment]
Can you feed this with latest master if it's not up to date or confirm it's ready to go?

**Comment by alundiak** [comment]
@gokaygurcan there was no conflicts between my branch and recent master, but I did rebase, and updated this PR.

**Comment by gokaygurcan** [comment]
No worries, had no time to check what was happened. If you're okay, I'm also okay with that. 
Cheers 🍻

**Pull request merged**
