### PR TITLE
Add "lookpath" package

### PR DESCRIPTION
**Pull request by otiai10**
# Background

When we google **"how to check if a command exists in nodejs"**, many inefficient ways are suggested with spawning subprocesses.

This package provides the simplest way to do that WITHOUT depending on other binaries.

# Links

discussion: https://stackoverflow.com/a/56321089/1368868
github.com repo: https://github.com/otiai10/lookpath
npmjs.org: https://www.npmjs.com/package/lookpath
coverage service link: https://codecov.io/gh/otiai10/lookpath

Thanks you for facilitating, you're awesome! 👍

### CODE REVIEW

**Comment by otiai10** [comment]
ping @sorrycc @gokaygurcan @hueitan @andreasonny83

**Comment by otiai10** [comment]
Hi @gokaygurcan , I saw some of your comments mentioning "not-acceptable for low-stared repos" policy.
I'm not that enthusiastic to get this PR merged 😅, but I want to know more "awesome" solution for this purpose. If you know something, please let me know 🙏

**Comment by andreasonny83** [comment]
I can agree with @gokaygurcan in saying this PR is not ready to be merged since the lookpath only holds a couple of stars.
I would suggest to close this issue for now and reopen in the future if that package become "awesome"

**Comment by otiai10** [comment]
@andreasonny83 Thank you for your comment. Sounds fair enough for me.
By the way, do you know better solution for this purpose? I need to know something "awesome" on this topic.

**Comment by andreasonny83** [comment]
All you can do is to promote `lookpath` and make sure the project gets a least 1k start on GitHub, then you should be able to re-open this ticket

**Pull request closed without merging**
