### PR TITLE
Add RiotJs to Non-MVC framworks list.

### PR DESCRIPTION
**Pull request by Bleeky**

### CODE REVIEW

**Comment by huei90** [comment]
@Bleeky Riot not a MVC framework? I already add Riot to MVC framework list.

**Comment by Bleeky** [comment]
It's not exactly a MVC framework, like React. It's called a MVP because the view isn't supposed to interact with the model.
admfr
t2kzd

**Comment by huei90** [comment]
@Bleeky You are right. Fighting MVC between non-MVC are useless. :beers:

**Comment by Bleeky** [comment]
Definitly ! :smiley:

**Pull request closed without merging**
