### PR TITLE
add the redux

### PR DESCRIPTION
**Pull request by silentMood**

### CODE REVIEW

**Comment by silentMood** [comment]
work great with the ant.d

**Comment by huei90** [comment]
I'm not sure this belongs to the section - MVC Frameworks and Libraries

**Comment by silentMood** [comment]
Well, it's hard to classify it. Mostly it just like the flux thing, control the data flow. it can work great with some view stuff. such as react, riot ... Some advice?

**Comment by silentMood** [comment]
So far, consider the section we have, I think it should belong to the Functional Programming. do you agree?

**Comment by silentMood** [comment]
redux sure is functional style

**Comment by silentMood** [comment]
Without the coding style, redux do some great job on the Application Architecture.

**Comment by huei90** [comment]
Ya, it's difficult to define here. Let's leave this pr for a while and see what's happen.

**Comment by silentMood** [comment]
Okey :)

**Comment by andreasonny83** [comment]
I recognize this is a bit late. However, if you fix the conflict, I'll be happy to merge your PR in @silentMood

**Comment by andreasonny83** [comment]
Closing since the author didn't fix the conflicts after 1 year

**Pull request closed without merging**
