### PR TITLE
added reference to yolpo's regression test

### PR DESCRIPTION
**Pull request by lorenzoongithub**

### CODE REVIEW

**Comment by huei90** [comment]
Thanks @lorenzoongithub yolpo is currently too young. 

I didn't see any source code on https://github.com/lorenzoongithub/yolpo
Wait until you open source yolpo, and send me again the PR and I will merge it :smile: 

:+1: nice project. Look forward to see it.

**Comment by lorenzoongithub** [comment]
@huei90 Your point is well taken. yolpo is indeed in its infancy.
I am planning to update it and put it on github pretty soon.
I will send you the PR once I am ready. Thanks

**Comment by huei90** [comment]
Ok, send me the PR once ready.

**Comment by lorenzoongithub** [comment]
@huei90 hi there, I have now committed the source code on https://github.com/lorenzoongithub/yolpo
will you merge the change now 
Thanks a lot

**Comment by huei90** [comment]
Nice project, but need more documentation and introduction, it's easier for others to understand them.

Welcome PR, I will merge it.

**Comment by lorenzoongithub** [comment]
@huei90 I appreciate that. More documentation will come over the next weeks.
thanks a lot

**Comment by lorenzoongithub** [comment]
@huei90 did you forget to merge my request ?

**Comment by huei90** [comment]
Sorry! Would you mind give the PR again?

**Comment by lorenzoongithub** [comment]
https://github.com/sorrycc/awesome-javascript/pull/106

**Comment by huei90** [comment]
Your PR has been deleted, I can't merge it.

**Pull request closed without merging**
