### PR TITLE
Added Codacy to the list of QA Tools

### PR DESCRIPTION
**Pull request by cog**

### CODE REVIEW

**Comment by huei90** [comment]
Thanks @cog But this looks like a **Service** not actually a tool to lint JavaScript Code.

**Comment by cog** [comment]
No, it's not a tool to lint JavaScript Code; it integrates JavaScript lint and breaks down the reports on a per-commit basis (so one can see the new issues instead of just a huge list with all of them); it does work as a service, and even though there's also an on-premises version I can definitely see your point.

I did notice that the list contained only lint tools, but I thought tools like this one could be added because the title of the section was QA Tools.

If that section is meant to lint tools only then Codacy might not fit there; should the title of the section change and another section be added?

**Comment by huei90** [comment]
Hi @cog Thanks for your clear explanation.
As you can see the list from **QA Tools**, the items are the **code** that able to install and execute to lint the code, which will see the result immediately, not including the CI env or any service, just local.

Also, there is a section [Coverage](https://github.com/sorrycc/awesome-javascript#coverage), the current items are istanbul, blanket and JSCover, there is no [coveralls.io](coveralls.io) in this section. Therefore, if adding **Codacy**, that means coveralls should exist in Coverage section and **Code Climate** should be included too.

**Coverage** is now supported SCALA, RUBY, JAVA, JAVASCRIPT, PYTHON, PHP, it's not JavaScript specific only. This is kind of debate, if I can add this, I will add to QA/Code Review/CI Service, but I think this should be referred to another awesome-x which covers all the Services (the service I mentioned before)

Hope this is clear and look forward to your reply.

**Comment by cog** [comment]
Having looked into the project again, you are absolutely right; I no longer think it belongs there.

Feel free to reject the pull request. Thanks for the patience and explanation.

**Comment by huei90** [comment]
btw, nice project :+1: 

:beers:

**Pull request closed without merging**
