### PR TITLE
feat(Maps): Add ArcGIS Maps SDK for JavaScript

### PR DESCRIPTION
**Pull request by maxpatiiuk**
Checklist:

- [x] I've read and understood [Contributing Guidelines](CONTRIBUTING.md).
- [x] I've added the new resource at the end of its section.
- [x] This resource is out there for a while, and actively maintained.
    - Has been actively maintained for ~20 years
- [x] This resource is popular enough and has at least a few hundred stars on GitHub.
   - 600+ starts in https://github.com/Esri/jsapi-resources/tree/main. 26k+ weekly npm downloads

---

Why it should be included:
One of the largest mapping libraries out there, from the largest GIS company in the world. Maintained and actively developed for ~20 years. 

Project description:
The ArcGIS Maps SDK for JavaScript is a powerful library designed to enable interactive web mapping experiences. Leveraging JavaScript, it allows developers to embed rich, spatially-enabled user interfaces in their web applications. The SDK provides a comprehensive suite of tools for displaying maps, querying and editing geospatial data, and performing advanced spatial analytics. With a focus on performance and flexibility, it supports both 2D and 3D mapping and is compatible with a wide variety of GIS data formats and services. For those familiar with web mapping, the ArcGIS Maps SDK for JavaScript offers an extensive, customizable platform to build upon, making it easier to integrate spatial data and mapping capabilities into your projects.

I linked to https://developers.arcgis.com/javascript/latest/, rather than GitHub repository (https://github.com/Esri/arcgis-js-api or https://github.com/Esri/jsapi-resources/tree/main) as it is much more useful for those starting with the library/evaluating it (has live demo, quick start tips, and extensive reference documentation). But if that is a problem, I can edit that

### CODE REVIEW

**Comment by maxpatiiuk** [comment]
Hi
Could you clarify the reason for closing this? 😊
Thanks

**Comment by gokaygurcan** [comment]
Hi,

I understand what project does, but I don't understand how this makes a good JavaScript resource. Feels more like a commercial project / advertisement than a resource imho.

Cheers,
G.

**Comment by maxpatiiuk** [comment]
> I understand what project does, but I don't understand how this makes a good JavaScript resource. Feels more like a commercial project / advertisement than a resource IMHO.

Maps SDK is available at no additional charge for many. [Terms](https://developers.arcgis.com/javascript/latest/licensing/)
The fact that it is by far the largest and most powerful maps SDK out there makes it a great JavaScript resource for some of the most powerful applications.

The [Maps section of awesome-javascript](https://github.com/sorrycc/awesome-javascript?tab=readme-ov-file#maps) already includes several lightweight mapping libraries (and a few that are deprecated or dead), but it is missing a solid heavy-duty option. Plus, the fact that Maps SDK has been around for more than a decade, and continues active development is a great plus for serious apps.

**Comment by hhkaos** [comment]
Hi @gokaygurcan !, 
First of all, thanks for putting this awesome list together. I was the one suggesting @maxpatiiuk's team do the PR. 

Just for clarification, I thought it would be OK to do the PR because I saw the wrapper on top of the Google Maps API + I didn't see anything in the contributing guidelines specifying that resources should be open source, but I respect that's an important aspect 😊👍. Are you OK if I update the contributing guidelines to mention that?

Is it OK to open an issue to check other open-source projects we have that might be a good fit? Or do you prefer me to send directly individual PRs? (some ideas I have in mind are: [esri-leaflet](https://github.com/esri/esri-leaflet), [koop](https://github.com/koopjs/koop), and [calcite-design-system](https://github.com/Esri/calcite-design-system)).

Thanks! 🙏

**Comment by gokaygurcan** [comment]
Hi @hhkaos,

It's @sorrycc deserving the credit, I'm merely clicking a few buttons here and there. With that said, more than half of the items in the list was there before I started clicking those buttons. I just didn't want to kill them and update the entire list, but started checking the new adds a bit closer. Over time, some died out and the link checker helped us to clean them. Many of them stayed, because of these reasons.

When it comes to the contributions, I think anything within JavaScript and/or TypeScript line is a good addition. If it requires me to click more than 3 times to get to the source code, I consider it a flaky one and the other factors come into play, such as popularity and age. With commercial projects, it's harder to reach the code even if it's open sourced. Even then, the repo has close to zero stars or watches and almost no traffic (issues, prs, etc). This clearly shows the code that's open doesn't "generate any value" for the viewer. It's only valuable within it's own use. I tend to reject these ones sadly. If the other examples are falling into the "good" bucket, feel free to open PRs and let's consider them. 

I hope this clears some of my thinking process. 

Best,
G.

**Pull request closed without merging**
