### PR TITLE
Typo in TOC for Images

### PR DESCRIPTION
**Pull request by mycaule**
- [x] Fix images link in Table of Contents.
- [x] The TOC is actually pretty outdated, Regenerate TOC
- [x] Delete one link, _"SlidesJS is obsolete and no longer maintained"_, see [nathansearles/slidesjs](https://github.com/nathansearles/slidesjs)

### CODE REVIEW

**Comment by gokaygurcan** [comment]
Feel free to update it accordingly. Making just a noun plural adds not much value if you think there're bigger changes needed in the table of content.

**Comment by mycaule** [comment]
Well the link didn't work before my change, so it is a simple but big improvement haha !

**Comment by gokaygurcan** [comment]
Let's wait for the infamous validator, and merge it then.
Cheers!

**Comment by mycaule** [comment]
Thanks I actually deleted the broken link and regen the TOC completely using this online tool.

The TOC looks ok, there were plenty of links missing under Utils.
https://luciopaiva.com/markdown-toc/

**Comment by mycaule** [comment]
(up) this is ready

**Comment by gokaygurcan** [comment]
It's nice work, don't get me wrong, but why we removed "utilities" and "ui" sections?

**Comment by mycaule** [comment]
Because it is not here anymore, I regenerated the summary based on what is on the document right now.

**Comment by mycaule** [comment]
Thanks, I have just indented UI and Utilities as groups as you recommended.

For the Utilities group it doesn't seem organized enough for me. It currently contains Files, Functional Programming, ... Machine Learning, ..., Benchmark.

**Comment by mycaule** [comment]
it's ready tell me what you think

**Comment by Ashe-reset** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Pull request closed without merging**
