### PR TITLE
Add Million.js

### PR DESCRIPTION
**Pull request by aidenybai**
Checklist:

- [x] I've read and understood [Contributing Guidelines](CONTRIBUTING.md).
- [x] I've added the new resource at the end of its section.
- [x] This resource is out there for a while, and actively maintained.
- [x] This resource is popular enough and has at least a few hundred stars on GitHub.

---

Million can be used as a MVC Framework/Library, and is used to build MVC Frameworks/Libraries.

[GitHub Repository](https://github.com/aidenybai/million) | [Documentation](https://million.js.org)

### CODE REVIEW

**Comment by aidenybai** [comment]
Any update on this PR?

**Comment by gokaygurcan** [comment]
Hi @aidenybai, 

Sorry for the delay. I'm on vacation, thus it's waiting.

**Comment by aidenybai** [comment]
Still pending approval

**Comment by gokaygurcan** [comment]
True, my bad. Done now. Thanks again!

**Pull request merged**
