### PR TITLE
Added Spotify SDK

### PR DESCRIPTION
**Pull request by xeBuz**
Added Spotify SDK

### CODE REVIEW

**Comment by huei90** [comment]
This section?
https://github.com/sorrycc/awesome-javascript#sdk

**Comment by xeBuz** [comment]
@huei90 I think this apply more to `Audio` but I can move it to `SDK`

**Comment by huei90** [comment]
:+1: Try it again. I can't merge now.

**Comment by xeBuz** [comment]
@huei90 :+1: done

**Comment by sergiolepore** [comment]
:clap:

**Comment by huei90** [comment]
:beers:

**Pull request merged**
