### PR TITLE
Add HyperApp.

### PR DESCRIPTION
**Pull request by jbucaran**
Add [HyperApp](https://github.com/hyperapp/hyperapp).

EDIT: Fix link.

### CODE REVIEW

**Comment by jbucaran** [comment]
Hi @rohmanhm! 👋 

Do you think we can add HyperApp to this list? 

Cheers.

**Comment by rohmanhm** [comment]
Absolutely yes. @hueitan

**Comment by jbucaran** [comment]
@rohmanhm Thank you! 🍻

**Comment by hueitan** [comment]
Sure 😄

**Comment by adar-w** [comment]
image

**Comment by adar-w** [comment]
![image](https://user-images.githubusercontent.com/12758600/28908498-97fa0a7e-7856-11e7-8087-871c1

**Pull request merged**
