### PR TITLE
Add fxts

### PR DESCRIPTION
**Pull request by ppeeou**
Checklist:

- [x] I've read and understood [Contributing Guidelines](CONTRIBUTING.md).
- [x] I've added the new resource at the end of its section.
- [x] This resource is out there for a while, and actively maintained.
- [x] This resource is popular enough and has at least a few hundred stars on GitHub.

---

There are functions that do exist not in the existing functional programming library.

fxts have a few features
- Simultaneous requests are possible, and concurrent situations can be created.
- Lazy evaluation is possible, It will consume "Iterable/asyncIterable" when it needs to be evaluated. so efficient calculation is attainable in declaratively written code.

### CODE REVIEW

**Comment by ppeeou** [comment]
@gokaygurcan Could you please check it out?

**Review by gokaygurcan — APPROVED** [review]

**Comment by ppeeou** [comment]
Since the test failed, proceeded to rebase the PR. check it out again please 🙇‍♂️ @gokaygurcan

**Comment by ppeeou** [comment]
The test failure doesn't seem to have anything to do with this PR

**Comment by gokaygurcan** [comment]
Thanks ^_^

**Pull request merged**
