### PR TITLE
add friendly

### PR DESCRIPTION
**Pull request by pjebs**

### CODE REVIEW

**Comment by pjebs** [comment]
@gokaygurcan any issues with this?

**Comment by gokaygurcan** [comment]
Besides from it's a 100% Go project? :)

**Comment by pjebs** [comment]
It's under the category of "## Developer Tools" specifically for javascript developers

**Comment by gokaygurcan** [comment]
I really don't want to be _that guy_ but it's not fitting into this definition: 
> A collection of awesome browser-side JavaScript libraries, resources and shiny things.

It's like adding https://github.com/FiloSottile/mkcert to this list. I understand its value and why it's helpful but this is just not the right place.

**Comment by pjebs** [comment]
is there an appeal process? i.e. others on your team.

> awesome browser-side shiny things

It seems like a shiny thing for javascript developers. As is mkcert. And the category: `Developer Tools` makes it clear it's not necessarily written in javascript per se.

**Comment by gokaygurcan** [comment]
First and foremost, I'm not the owner of this repository, you can always reach out to @sorrycc if you want. And I'm sure there're other collaborators, you can find easily from other tabs. 

In the past, there were discussions about allowing low-starred repositories or not accepting them. Considering suggested repository has 10 stars, it's not a common _developer tool_. Nevertheless, we added a lot of low profile projects because they were written in JavaScript or were directly a part of JavaScript ecosystem. mkcert is a platform-agnostic solution for something common in development phase, it is a very well developer tool in that sense, but still not something for this list. 

friendly, on the other hand, doesn't tick any of these checkboxes. I still don't understand why you're pushing this hard? If you just want to add a local server with ssl support, go with [Caddy](https://github.com/caddyserver/caddy), it's at least well known and somewhat common alternative (and written in Go). Or if you want to stick with JavaScript, even if it's a very very very low profile project, go with http-server-ssl package (fork of somewhat common http-server package with https support). 

But again, this is my personal opinion.

**Pull request closed without merging**
