### PR TITLE
Added Tabulator and Bootstrap Table to the Table/Grid section

### PR DESCRIPTION
**Pull request by olifolkerd**

### CODE REVIEW

**Comment by olifolkerd** [comment]
Hi @rohmanhm

Do you think that Tabulator would be a good addition to this list?

Cheers

Oli

**Comment by rohmanhm** [comment]
Of course. But I think it will be nice if you separate adding new list per commit/PR 🙂.

note: I'm not author of this awesome repo. @hueitan knows better than me

**Comment by olifolkerd** [comment]
Hi @hueitan 

Do you think that Tabulator would be a good addition to this list?

Cheers

Oli

**Comment by olifolkerd** [comment]
Hey @andreasonny83

Do you think that Tabulator would be a good addition to this list?

Cheers

Oli

**Comment by andreasonny83** [comment]
Yes @olifolkerd . I think they are both cool enough to go in this project.
I can accept your PR.

**Pull request merged**
