### PR TITLE
MAJOR update to README.md

### PR DESCRIPTION
**Pull request by klutchdev**
@nelix @azer @Knorcedger @Namek @snd 
**I fixed EVERYTHING because as of now its broken completely. 
Please merge! Thank you! **
#720 #719 

Screen Shot 2020-09-05 at 4 45 50 AM

Screen Shot 2020-09-05 at 4 45 39 AM

### CODE REVIEW

**Comment by gokaygurcan** [comment]
Why all this drama?

**Comment by klutchdev** [comment]
@gokaygurcan no drama, just trying to help keep awesome awesome not awesome broken. cheers🔥

**Comment by gokaygurcan** [comment]
This might still be relevant. I directly committed to `master` to fix the actual problem but i liked what you did here to make it more consistent across the file. Let's talk about it and hopefully get it merged ^_^

**Comment by klutchdev** [comment]
Oh sorry about that!!
I am glad that you find it useful and always happy to help. I won't touch
anything unless you tell me. haha!
have a great day!

**Pull request closed without merging**
