### PR TITLE
Fixing link to GraphicsJS

### PR DESCRIPTION
**Pull request by spekulatius**
Hey @sorrycc 

just fixing the link to GraphicsJS.

Cheers!

### CODE REVIEW

**Comment by gokaygurcan** [comment]
Hi @spekulatius,

Thanks for your contribution but i'm not really sure why we're changing the existing url, which belongs to the same project already. Can you explain what you are _fixing_ here a bit?

**Comment by spekulatius** [comment]
Hey @gokaygurcan 

the existing link gives me an SSL error:

image

You aren't getting the error?

Cheers,
Peter

**Comment by gokaygurcan** [comment]
I used the link on GitHub project, http://www.graphicsjs.org/, with http and it's working fine. It's http, you can argue about that, but it doesn't change the URL's validity. If i try with https, it gives an ssl error and redirects to the company page, yes.

So the question here is, which link should be added: their own homepage with http or repository url?

**Comment by spekulatius** [comment]
Interesting, I assumed I got redirected by the server and ignored the original protocol. If it works for you I guess my browser must have redirected me. Maybe some setting I'm unaware of caused it. 

Regarding your question: yes, that's the question. What do you think?

**Comment by gokaygurcan** [comment]
yea, i feel good today, let's accept it.

**Review by gokaygurcan — CHANGES_REQUESTED** [review]
thanks!

**Review by gokaygurcan — APPROVED** [review]

**Comment by spekulatius** [comment]
Thank you @gokaygurcan

**Pull request merged**
